from __future__ import annotations

from datetime import date, timedelta


def _days_ago(days: int) -> str:
    return (date.today() - timedelta(days=days)).isoformat()


SAMPLE_CLIENTS = [
    {
        "name": "Sarah Johnson",
        "email": "sarah.johnson@example.com",
        "phone": "414-555-0111",
        "start_date": _days_ago(120),
        "last_contact": _days_ago(3),
        "last_session": _days_ago(5),
        "goals": "Career transition planning and confidence.",
        "notes": "Responds well to action-oriented check-ins.",
        "engagement_score": 85,
        "churn_risk": "LOW",
        "mood_trend": "🙂 Motivated",
        "next_action": "Share weekly planning template.",
    },
    {
        "name": "Michael Chen",
        "email": "michael.chen@example.com",
        "phone": "414-555-0112",
        "start_date": _days_ago(95),
        "last_contact": _days_ago(9),
        "last_session": _days_ago(12),
        "goals": "Work-life balance and stress management.",
        "notes": "Missed last two optional check-ins.",
        "engagement_score": 45,
        "churn_risk": "HIGH",
        "mood_trend": "😕 Stressed",
        "next_action": "Send supportive re-engagement message.",
    },
    {
        "name": "Emily Rodriguez",
        "email": "emily.rodriguez@example.com",
        "phone": "414-555-0113",
        "start_date": _days_ago(140),
        "last_contact": _days_ago(2),
        "last_session": _days_ago(3),
        "goals": "Relationship coaching and communication.",
        "notes": "Strong momentum from recent sessions.",
        "engagement_score": 92,
        "churn_risk": "LOW",
        "mood_trend": "😊 Positive",
        "next_action": "Celebrate latest milestone.",
    },
    {
        "name": "David Park",
        "email": "david.park@example.com",
        "phone": "414-555-0114",
        "start_date": _days_ago(70),
        "last_contact": _days_ago(14),
        "last_session": _days_ago(18),
        "goals": "Leadership development and delegation.",
        "notes": "Needs accountability around follow-through.",
        "engagement_score": 30,
        "churn_risk": "HIGH",
        "mood_trend": "😞 Disengaged",
        "next_action": "Offer short low-pressure reconnect session.",
    },
    {
        "name": "Lisa Thompson",
        "email": "lisa.thompson@example.com",
        "phone": "414-555-0115",
        "start_date": _days_ago(80),
        "last_contact": _days_ago(7),
        "last_session": _days_ago(9),
        "goals": "Health and wellness consistency.",
        "notes": "Motivated but schedule has been inconsistent.",
        "engagement_score": 55,
        "churn_risk": "MEDIUM",
        "mood_trend": "😐 Mixed",
        "next_action": "Suggest habit tracker refresh.",
    },
    {
        "name": "James Wilson",
        "email": "james.wilson@example.com",
        "phone": "414-555-0116",
        "start_date": _days_ago(150),
        "last_contact": _days_ago(1),
        "last_session": _days_ago(2),
        "goals": "Financial confidence and planning.",
        "notes": "Very proactive between sessions.",
        "engagement_score": 95,
        "churn_risk": "LOW",
        "mood_trend": "🚀 Thriving",
        "next_action": "Introduce advanced goal setting worksheet.",
    },
    {
        "name": "Amanda Foster",
        "email": "amanda.foster@example.com",
        "phone": "414-555-0117",
        "start_date": _days_ago(60),
        "last_contact": _days_ago(12),
        "last_session": _days_ago(15),
        "goals": "Career pivot and interview readiness.",
        "notes": "Confidence dipped after a rejected application.",
        "engagement_score": 40,
        "churn_risk": "HIGH",
        "mood_trend": "😟 Uncertain",
        "next_action": "Share confidence-building win recap.",
    },
    {
        "name": "Robert Kim",
        "email": "robert.kim@example.com",
        "phone": "414-555-0118",
        "start_date": _days_ago(110),
        "last_contact": _days_ago(4),
        "last_session": _days_ago(6),
        "goals": "Entrepreneurship and decision clarity.",
        "notes": "Consistent attendance, asks strong questions.",
        "engagement_score": 88,
        "churn_risk": "LOW",
        "mood_trend": "🙂 Focused",
        "next_action": "Send strategic prioritization exercise.",
    },
]


SAMPLE_INTERACTIONS = [
    {"client_name": "Sarah Johnson", "days_ago": 2, "type": "Check-in", "notes": "Completed goals worksheet.", "sentiment": "Positive"},
    {"client_name": "Sarah Johnson", "days_ago": 6, "type": "Session", "notes": "Clarified top 3 priorities.", "sentiment": "Positive"},
    {"client_name": "Michael Chen", "days_ago": 4, "type": "Email", "notes": "Did not reply to follow-up email.", "sentiment": "Negative"},
    {"client_name": "Michael Chen", "days_ago": 11, "type": "Session", "notes": "Reported high workload stress.", "sentiment": "Mixed"},
    {"client_name": "Emily Rodriguez", "days_ago": 1, "type": "Check-in", "notes": "Celebrated communication win.", "sentiment": "Positive"},
    {"client_name": "Emily Rodriguez", "days_ago": 5, "type": "Session", "notes": "Practiced conflict script.", "sentiment": "Positive"},
    {"client_name": "David Park", "days_ago": 10, "type": "Email", "notes": "Delayed goals update.", "sentiment": "Negative"},
    {"client_name": "David Park", "days_ago": 16, "type": "Session", "notes": "Discussed blocked priorities.", "sentiment": "Neutral"},
    {"client_name": "Lisa Thompson", "days_ago": 3, "type": "Check-in", "notes": "Re-started wellness routine.", "sentiment": "Positive"},
    {"client_name": "Lisa Thompson", "days_ago": 8, "type": "Session", "notes": "Needs better schedule boundaries.", "sentiment": "Mixed"},
    {"client_name": "James Wilson", "days_ago": 1, "type": "Email", "notes": "Shared budgeting milestones.", "sentiment": "Positive"},
    {"client_name": "James Wilson", "days_ago": 7, "type": "Session", "notes": "Prepared next quarter plan.", "sentiment": "Positive"},
    {"client_name": "Amanda Foster", "days_ago": 6, "type": "Check-in", "notes": "Confidence dropped this week.", "sentiment": "Negative"},
    {"client_name": "Amanda Foster", "days_ago": 13, "type": "Session", "notes": "Reviewed interview strategy.", "sentiment": "Mixed"},
    {"client_name": "Robert Kim", "days_ago": 2, "type": "Session", "notes": "Validated business priorities.", "sentiment": "Positive"},
    {"client_name": "Robert Kim", "days_ago": 9, "type": "Email", "notes": "Requested accountability touchpoint.", "sentiment": "Positive"},
]
