from __future__ import annotations

from datetime import date, timedelta


def days_ago(days: int) -> str:
    return (date.today() - timedelta(days=days)).isoformat()


SAMPLE_CONTACTS = [
    {
        "name": "Sarah Johnson",
        "email": "sarah.j@techcorp.com",
        "phone": "555-0101",
        "company": "TechCorp Inc.",
        "title": "VP of Operations",
        "linkedin_url": "https://linkedin.com/in/sarahjohnson",
        "source": "BNI",
        "start_date": days_ago(150),
        "last_contact": days_ago(3),
        "last_interaction": days_ago(4),
        "objectives": "Process automation and team efficiency",
        "notes": "Warm intro through business network.",
        "engagement_score": 85,
        "follow_up_priority": "LOW",
        "engagement_sentiment": "😊 Strong",
        "next_action": "Share operations benchmarking resource.",
        "tags": "enterprise,warm-intro",
    },
    {
        "name": "Michael Chen",
        "email": "mchen@startup.io",
        "phone": "555-0102",
        "company": "StartupIO",
        "title": "Founder and CEO",
        "linkedin_url": "https://linkedin.com/in/mchen",
        "source": "Referral",
        "start_date": days_ago(98),
        "last_contact": days_ago(11),
        "last_interaction": days_ago(13),
        "objectives": "Scaling operations and investor updates",
        "notes": "High value contact, needs timely follow-up.",
        "engagement_score": 45,
        "follow_up_priority": "HIGH",
        "engagement_sentiment": "😟 Declining",
        "next_action": "Schedule short call in next 48 hours.",
        "tags": "startup,high-value",
    },
    {
        "name": "Emily Rodriguez",
        "email": "emily@brightpartners.co",
        "phone": "555-0103",
        "company": "Bright Partners",
        "title": "Partnership Director",
        "linkedin_url": "https://linkedin.com/in/emilyrodriguez",
        "source": "Cold Outreach",
        "start_date": days_ago(120),
        "last_contact": days_ago(2),
        "last_interaction": days_ago(2),
        "objectives": "Co-marketing opportunities",
        "notes": "Responsive and collaborative.",
        "engagement_score": 92,
        "follow_up_priority": "LOW",
        "engagement_sentiment": "🚀 Growing",
        "next_action": "Draft co-hosted webinar outline.",
        "tags": "partnership,active",
    },
    {
        "name": "David Park",
        "email": "david@northstarlogistics.com",
        "phone": "555-0104",
        "company": "Northstar Logistics",
        "title": "Operations Lead",
        "linkedin_url": "https://linkedin.com/in/davidpark",
        "source": "BNI",
        "start_date": days_ago(81),
        "last_contact": days_ago(15),
        "last_interaction": days_ago(18),
        "objectives": "Vendor workflow optimization",
        "notes": "Email opened, no reply yet.",
        "engagement_score": 35,
        "follow_up_priority": "HIGH",
        "engagement_sentiment": "😐 Mixed",
        "next_action": "Send concise status recap and CTA.",
        "tags": "operations,re-engage",
    },
    {
        "name": "Lisa Thompson",
        "email": "lisa@wellsuitegroup.com",
        "phone": "555-0105",
        "company": "WellSuite Group",
        "title": "Managing Partner",
        "linkedin_url": "https://linkedin.com/in/lisathompson",
        "source": "Referral",
        "start_date": days_ago(105),
        "last_contact": days_ago(8),
        "last_interaction": days_ago(9),
        "objectives": "Service packaging and pricing review",
        "notes": "Interested but timeline uncertain.",
        "engagement_score": 58,
        "follow_up_priority": "MEDIUM",
        "engagement_sentiment": "🙂 Stable",
        "next_action": "Offer two package options by email.",
        "tags": "services,proposal",
    },
    {
        "name": "James Wilson",
        "email": "james@finpilot.io",
        "phone": "555-0106",
        "company": "FinPilot",
        "title": "Head of Growth",
        "linkedin_url": "https://linkedin.com/in/jameswilson",
        "source": "LinkedIn",
        "start_date": days_ago(165),
        "last_contact": days_ago(1),
        "last_interaction": days_ago(1),
        "objectives": "Joint lead generation campaign",
        "notes": "Consistent response rate.",
        "engagement_score": 95,
        "follow_up_priority": "LOW",
        "engagement_sentiment": "🔥 Excellent",
        "next_action": "Share campaign timeline draft.",
        "tags": "growth,strategic",
    },
    {
        "name": "Amanda Foster",
        "email": "amanda@careerpivotlabs.com",
        "phone": "555-0107",
        "company": "Career Pivot Labs",
        "title": "Founder",
        "linkedin_url": "https://linkedin.com/in/amandafoster",
        "source": "Conference",
        "start_date": days_ago(74),
        "last_contact": days_ago(12),
        "last_interaction": days_ago(16),
        "objectives": "Partnership onboarding workflow",
        "notes": "Needs clearer implementation timeline.",
        "engagement_score": 42,
        "follow_up_priority": "HIGH",
        "engagement_sentiment": "😕 At Risk",
        "next_action": "Send 3-step onboarding plan.",
        "tags": "founder,priority",
    },
    {
        "name": "Robert Kim",
        "email": "robert@ventureforge.ai",
        "phone": "555-0108",
        "company": "VentureForge AI",
        "title": "Co-founder",
        "linkedin_url": "https://linkedin.com/in/robertkim",
        "source": "Mutual Connection",
        "start_date": days_ago(132),
        "last_contact": days_ago(4),
        "last_interaction": days_ago(5),
        "objectives": "Go-to-market planning support",
        "notes": "Strong momentum and quick feedback loops.",
        "engagement_score": 88,
        "follow_up_priority": "LOW",
        "engagement_sentiment": "😊 Positive",
        "next_action": "Prepare GTM checklist for review.",
        "tags": "ai,founder",
    },
]


SAMPLE_INTERACTIONS = [
    {"contact_name": "Sarah Johnson", "days_ago": 2, "type": "Email", "channel": "Gmail", "notes": "Requested timeline update.", "sentiment": "Positive", "ai_summary": "Contact asked for implementation timeline.", "follow_up_required": False},
    {"contact_name": "Sarah Johnson", "days_ago": 6, "type": "Meeting", "channel": "Calendar", "notes": "Reviewing operations KPI baseline.", "sentiment": "Positive", "ai_summary": "Meeting confirmed KPI priorities.", "follow_up_required": True},
    {"contact_name": "Michael Chen", "days_ago": 5, "type": "Email", "channel": "Gmail", "notes": "No response to pilot proposal.", "sentiment": "Negative", "ai_summary": "Proposal stalled, no reply received.", "follow_up_required": True},
    {"contact_name": "Emily Rodriguez", "days_ago": 1, "type": "LinkedIn", "channel": "LinkedIn", "notes": "Shared collaboration post.", "sentiment": "Positive", "ai_summary": "Engagement signal is strong.", "follow_up_required": False},
    {"contact_name": "David Park", "days_ago": 11, "type": "Call", "channel": "Manual", "notes": "Call postponed to next week.", "sentiment": "Neutral", "ai_summary": "Need to reschedule with clear agenda.", "follow_up_required": True},
    {"contact_name": "Lisa Thompson", "days_ago": 7, "type": "Meeting", "channel": "Calendar", "notes": "Discussed scope and budget.", "sentiment": "Mixed", "ai_summary": "Interested but budget timing uncertain.", "follow_up_required": True},
    {"contact_name": "James Wilson", "days_ago": 2, "type": "Email", "channel": "Gmail", "notes": "Approved campaign draft.", "sentiment": "Positive", "ai_summary": "Ready for next implementation step.", "follow_up_required": False},
    {"contact_name": "Amanda Foster", "days_ago": 9, "type": "LinkedIn", "channel": "LinkedIn", "notes": "Viewed profile but no message.", "sentiment": "Neutral", "ai_summary": "Soft intent, requires proactive outreach.", "follow_up_required": True},
    {"contact_name": "Robert Kim", "days_ago": 3, "type": "Meeting", "channel": "Calendar", "notes": "Aligned on milestones.", "sentiment": "Positive", "ai_summary": "Momentum is healthy and active.", "follow_up_required": False},
]
